package com.bookmanagement.model;
// Generated 20 Jul, 2018 11:20:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Library generated by hbm2java
 */
@Entity
@Table(name="library"
    ,catalog="bookmanagement"
)
public class Library  implements java.io.Serializable {


     private Long libraryId;
     private User user;
     private String name;
     private Date createdDate;
     private Character isActive;
     private Set<LibraryBook> libraryBooks = new HashSet<LibraryBook>(0);

    public Library() {
    }

    public Library(User user, String name, Date createdDate, Character isActive, Set<LibraryBook> libraryBooks) {
       this.user = user;
       this.name = name;
       this.createdDate = createdDate;
       this.isActive = isActive;
       this.libraryBooks = libraryBooks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="library_id", unique=true, nullable=false)
    public Long getLibraryId() {
        return this.libraryId;
    }
    
    public void setLibraryId(Long libraryId) {
        this.libraryId = libraryId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id")
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="name", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date", length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="is_active", length=1)
    public Character getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Character isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="library")
    public Set<LibraryBook> getLibraryBooks() {
        return this.libraryBooks;
    }
    
    public void setLibraryBooks(Set<LibraryBook> libraryBooks) {
        this.libraryBooks = libraryBooks;
    }




}


