package com.bookmanagement.model;
// Generated 20 Jul, 2018 11:20:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="bookmanagement"
)
public class User  implements java.io.Serializable {


     private Long userId;
     private String name;
     private Date dob;
     private Date createdDate;
     private Character isActive;
     private Set<Library> libraries = new HashSet<Library>(0);
     private Set<Book> books = new HashSet<Book>(0);

    public User() {
    }

    public User(String name, Date dob, Date createdDate, Character isActive, Set<Library> libraries, Set<Book> books) {
       this.name = name;
       this.dob = dob;
       this.createdDate = createdDate;
       this.isActive = isActive;
       this.libraries = libraries;
       this.books = books;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="user_id", unique=true, nullable=false)
    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dob", length=10)
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date", length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="is_active", length=1)
    public Character getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Character isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Library> getLibraries() {
        return this.libraries;
    }
    
    public void setLibraries(Set<Library> libraries) {
        this.libraries = libraries;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Book> getBooks() {
        return this.books;
    }
    
    public void setBooks(Set<Book> books) {
        this.books = books;
    }




}


